[workspace]
members = [
    ".",
    "unassigned",
    "packages/intake",
    "packages/intake/packages/nose-cone",
    "packages/intake/packages/intake-casing",
    "packages/intake/packages/intake-structure",
    "packages/intake/packages/intake-fan",
    "packages/compressor",
    "packages/compressor/packages/front-compressor",
    "packages/compressor/packages/front-compressor/packages/front-compression-cap",
    "packages/compressor/packages/front-compressor/packages/front-compression-hub",
    "packages/compressor/packages/front-compressor/packages/front-compression-fan-1",
    "packages/compressor/packages/front-compressor/packages/front-compression-fan-2",
    "packages/compressor/packages/front-compressor/packages/front-compression-fan-3",
    "packages/compressor/packages/front-compressor/packages/front-compression-fan-4",
    "packages/compressor/packages/mid-compressor",
    "packages/compressor/packages/mid-compressor/packages/mid-compression-cap",
    "packages/compressor/packages/mid-compressor/packages/mid-compression-fan",
    "packages/compressor/packages/mid-compressor/packages/mid-compression-link",
    "packages/compressor/packages/mid-compressor/packages/mid-compression-shaft",
    "packages/compressor/packages/mid-compressor/packages/mid-axis-cover",
    "packages/compressor/packages/rear-compressor",
    "packages/compressor/packages/rear-compressor/packages/rear-compression-fan-1",
    "packages/compressor/packages/rear-compressor/packages/rear-compression-fan-2",
    "packages/compressor/packages/rear-compressor/packages/rear-compression-fan-3",
    "packages/compressor/packages/rear-compressor/packages/rear-compression-hub",
    "packages/compressor/packages/rear-compressor/packages/rear-compression-link",
    "packages/compressor/packages/rear-compressor/packages/rear-compression-structure",
    "packages/combustion-system",
    "packages/combustion-system/packages/combustion-casing",
    "packages/combustion-system/packages/combustion-chamber",
    "packages/combustion-system/packages/combustion-c-ring",
    "packages/combustion-system/packages/combustion-shell",
    "packages/combustion-system/packages/combustion-cap",
    "packages/combustion-system/packages/combustion-stage",
    "packages/combustion-system/packages/fuel-port-cap",
    "packages/main-axis",
    "packages/main-axis/packages/main-axis-shaft",
    "packages/main-axis/packages/bearing-1",
    "packages/main-axis/packages/bearing-2",
    "packages/main-axis/packages/turbine-axis-spacer",
    "packages/turbine",
    "packages/turbine/packages/turbine-shaft",
    "packages/turbine/packages/turbine-housing",
    "packages/turbine/packages/turbine-fan-1",
    "packages/turbine/packages/turbine-fan-2",
    "packages/turbine/packages/turbine-fan-3",
    "packages/turbine/packages/turbine-fan-4",
    "packages/turbine/packages/turbine-fan-5",
    "packages/turbine/packages/turbine-fan-6",
    "packages/turbine/packages/turbine-spacer-1",
    "packages/turbine/packages/turbine-spacer-2",
    "packages/turbine/packages/turbine-link",
    "packages/turbine/packages/turbine-link-assembly",
    "packages/exhaust",
    "packages/exhaust/packages/flare-base",
    "packages/exhaust/packages/flare-lever-1",
    "packages/exhaust/packages/flare-lever-2",
    "packages/exhaust/packages/flare-lever-3",
    "packages/structure",
    "packages/structure/packages/rear-casing",
    "packages/structure/packages/core-plate",
    "packages/structure/packages/heat-ring",
    "packages/structure/packages/rivet-2x4",
]
